models:
  - name: products
    description: 製品概要データマート。各製品の詳細情報を提供します。製品1つにつき1行です。
    columns:
      - name: product_id
        description: 製品のユニークキー
        data_tests:
          - not_null
          - unique
      - name: product_name
        description: 製品名
      - name: product_type
        description: 製品タイプ
      - name: product_description
        description: 製品説明
      - name: is_food_item
        description: 食品アイテムかどうかを示すブール値
      - name: is_drink_item
        description: ドリンクアイテムかどうかを示すブール値
      - name: product_price
        description: 製品価格
    meta:
      metrics:
        product_count:
          label: 製品数
          type: count_distinct
          sql: ${TABLE}.product_id
        average_product_price:
          label: 平均製品価格
          type: average
          sql: ${TABLE}.product_price
        food_product_count:
          label: 食品製品数
          type: count_distinct
          sql: case when ${TABLE}.is_food_item then ${TABLE}.product_id else null end
        drink_product_count:
          label: ドリンク製品数
          type: count_distinct
          sql: case when ${TABLE}.is_drink_item then ${TABLE}.product_id else null end
